// ==UserScript==
// @name         Database Answers
// @namespace    https://github.com/Wolferine3
// @version      1.0
// @description  Database for answers on AMQ trivia
// @author       Wolferine
// @match        https://animemusicquiz.com/*
// ==/UserScript==

const answer = ["2",
"Mahoromatic: Automatic Maiden",
"Azumanga Daioh",
"Dual! Parallel Trouble Adventure",
"Mermaid Melody: Pichi Pichi Pitch",
"Romance of Three Kingdoms",
"2",
"1988",
"7SEEDS",
"KSUKE feat. Tyler Carter",
"7",
"Carole & Tuesday",
"Blade & Soul",
"Katekyo Hitman Reborn!",
"Otome wa Boku ni Koishiteru: Futari no Elder",
"Casshan",
"Gunslinger Girl",
"A Certain Magical Index",
"60000000",
"Mobile Suit Gundam Wing",
"Revolutionary Girl Utena",
"12",
"Moribito: Guardian of the Spirit",
"The Slayers",
"5",
"Clannad",
"The Prince of Tennis",
"Sorcerer Hunters",
"Inuyasha",
"Ceres, Celestial Legend",
"Un-Go",
"Maria Holic",
"Knight Hunters",
"dis-",
"Howl's Moving Castle",
"1971",
"8",
"Cowboy Bebop",
"Truth",
"Francesca",
"5",
"Kaori Fukuhara",
"3",
"Akiba's Trip: The Animation",
"45",
"Fortune Carat",
"7",
"Ruri Umino",
"Hime Chen! Otogi Chikku Idol Lilpri",
"StarRing",
"Kaori Nazuka",
"Angel Beats!",
"Gunbuster",
"Yu Yu Hakusho",
"5000000",
"Humanity Has Declined",
"19300000000",
"Munto",
"Tetrarkhia",
"3",
"9",
"2030",
"40",
"Katharon",
"Blumenkranz",
"Magical Circle Guru-Guru",
"His and Her Circumstances",
"Million Doll",
"7",
"20",
"1",
"9",
"Urusei Yatsura: Beautiful Dreamer",
"Magical Princess Minky Momo",
"Yui Ogura",
"Hulaing Babies",
"Yu-Gi-Oh! Zexal",
"2",
"Akiyama Mio",
"Kashimashi: Girl Meets Girl",
"Darker than Black",
"Ryuu no Haisha",
"Shinryaku!? Ika Musume",
"Gintoki and Shinpachi",
"10",
"Amagi Brilliant Park",
"39",
"12858051967633865",
"Touka Gettan",
"Tenran",
"11",
"Rabbit",
"G Gundam",
"rain tears",
"15532",
"My Neighbor Totoro",
"Hargeon",
"Pepe Gundam",
"The Two Earths",
"1973",
"Naomi Tanizaki",
"Emiya Shirou",
"Sora Amamiya (Aqua)",
"Moses",
"3",
"9",
"Eir Aoi",
"78",
"Wonderland",
"Liberation Knights",
"Eien no Basara",
"Ame Saga",
"Onaro Gara",
"Shika Uno",
"Sakura Nakajima",
"Akito",
"Musume Paradise",
"I.K.M",
"Imaginary Friend",
"Yes! Happy! Go!",
"My Love Near Me",
"all of you",
"Hello Bang Bang!",
"I'm Trying to Take Revenge on my Sister for Matching me with her Crazy Friend but she Ends up Liking it?!",
"Afterglow",
"Uta no Prince-sama",
"Koi to Producer: EVOL×LOVE",
"2008",
"Kimagure Orange Road",
"Mikuru",
"119",
"Yamamoto Takeshi",
"Fortune Arterial: Akai Yakusoku",
"1997",
"2003",
"103000",
"Inuyasha",
"Kasukabe",
"Cat",
"Come",
"Envy",
"The witch of the waste",
"Godchild",
"Emporio Ivankov",
"A crystal dagger",
"To be loved by someone",
"Zarbon",
"Samurai Champloo",
"Danganronpa The Animation",
"Problem children are coming from another world, aren't they?",
"Service Club",
"3/4",
"Nishijima Masumi",
"Sloth",
"Dance Dance Revolution",
"India",
"Cigarette",
"9,3"];
